server:
  port: ${PORT:5000}
spring:
  application-name: API-GATEWAY



  cloud:
    gateway:
      routes:
        - id: SUSER-SERVICE
          uri: lb://SUSER-SERVICE
          predicates:
            - Path=/sw/users/**

        - id: SGROUPS-SERVICE
          uri: lb://SGROUPS-SERVICE
          predicates:
            - Path=/sw/groups/**

        - id: SBILLS-SERVICE
          uri: lb://SBILLS-SERVICE
          predicates:
            - Path=/sw/bills/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://splitwiseeureka-env.eba-qp57xgcp.eu-north-1.elasticbeanstalk.com/eureka