server:
  port: 8090
spring:
  application-name: API-GATEWAY



  cloud:
    gateway:
      routes:
        - id: SUSER-SERVICE
          uri: lb://SUSER-SERVICE
          predicates:
            - Path=/sw/users/**

        - id: SGROUPS-SERVICE
          uri: lb://SGROUPS-SERVICE
          predicates:
            - Path=/sw/groups/**

        - id: SBILLS-SERVICE
          uri: lb://SBILLS-SERVICE
          predicates:
            - Path=/sw/bills/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka